from django.urls import path
from motoapp import views

urlpatterns = [
    path('login',views.user_login),
    path('logout',views.ulogout),
    path('register',views.register),
    path('header',views.header),
    path('home',views.home),
    path('test',views.test),
    path('bss',views.bss),
    path('selling',views.selling,name='selling'),
    path('sell_form',views.sell_form,name='sell_form'),
    path('sell_details/<int:pk>/',views.sell_details,name='sell_details'),
    path('buy_details/<int:pk>/',views.buy_details,name='buy_details'),
    path('range',views.range,name='range'),
    path('range1',views.range1,name='range1'),
    path('sort/<sv>',views.sort),
    path('sort1/<sv>',views.sort1),
    path('buy12'    ,views.buy12,name='buy12'),
    path('buying',views.buying,name='buying'),
    path('addtocart/<pid>',  views.addtocart),
    path('cart',views.cart),
    path('remove/<uid>',views.remove),
    path('remove_order/<uid>',views.remove_order),
    path('sendquote/<pid>/', views.sendquote, name='sendquote'),
    path('updateqty/<qv>/<cid>',views.updateqty),
    path('checkout',views.checkout,name='checkout'),
    path('update_user',views.update_user, name='update_user'),
    path('update_info',views.update_info, name='update_info'),
    path('billing_info',views.billing_info, name='billing_info'),
    path('billing_info',views.billing_info, name='billing_info'),
    path('search',views.search,name='search'),
    path('search1',views.search1,name='search1'),
    path('makepayment',views.makepayment),
    path('sendusermail',views.sendusermail),
    path('email',views.email),
    path('service_dashboard',views.service_dashboard,name='service_dashboard'),
    path('customer-add-request',views.customer_add_request_view,name='customer-add-request'),
    path('customer-view-request',views.customer_view_request_view,name='customer-view-request'),
    path('customer-delete-request/<int:pk>', views.customer_delete_request_view,name='customer-delete-request'),
    path('customer-view-approved-request',views.customer_view_approved_request_view,name='customer-view-approved-request'),
    path('customer-view-approved-request-invoice',views.customer_view_approved_request_invoice_view,name='customer-view-approved-request-invoice'),
    path('contact',views.contact,name='contact')
   
]