# Generated by Django 5.0.4 on 2024-04-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('Fuel_Type', models.CharField(choices=[('none', 'Select Fuel type'), ('cng_hybrid', 'CNG and Hybrid'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('lpg', 'LPG'), ('petrol', 'Petrol'), ('none', 'none')], default='none', max_length=20)),
                ('Mileage', models.CharField(max_length=100)),
                ('Power', models.CharField(max_length=100)),
                ('Launch_Date', models.CharField(max_length=100)),
                ('Engine_Capacity', models.CharField(max_length=100)),
                ('bdescription', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('Tyre', models.CharField(max_length=100)),
                ('bcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motoapp.bcategory')),
            ],
        ),
    ]
