# Generated by Django 5.0.4 on 2024-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoapp', '0006_alter_cart_pid_alter_cart_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
